version: '3.8'

services:
  web:
    image: web
    environment:
      - ALLOW_OVERRIDE=true
      - SECRET_KEY=${SECRET_KEY}
      - SECRET_IV=${SECRET_IV}
      - SECRET_METHOD=${SECRET_METHOD}
    ports:
      - "81:443"
    links:
      - db
    volumes:
      - ./app:/var/www/html/
      - ./cert:/etc/ssl/
      - ./localhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./app/logs:/var/www/html/logs
    command: /bin/bash -c "chown -R www-data:www-data /var/www/html/logs && apache2-foreground"
  db:
    image: mariadb:10.8.2
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
    ports:
      - "8889:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    links:
      - db
    ports:
      - 8890:80
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: database
